import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, AreaChart, Area, CartesianGrid } from "recharts";
const palette = ["#315c4d", "#b7833f", "#8b5e55", "#526b7a", "#8b8d74", "#6b4f5f"];
export function MonthlyBar({ data }) {
    return _jsx("div", { className: "chart", children: _jsx(ResponsiveContainer, { width: "100%", height: 260, children: _jsxs(BarChart, { data: data, margin: { top: 8, right: 10, left: -18, bottom: 0 }, children: [_jsx(CartesianGrid, { vertical: false, stroke: "var(--line)" }), _jsx(XAxis, { dataKey: "month", stroke: "var(--muted)", tickLine: false, axisLine: false }), _jsx(YAxis, { stroke: "var(--muted)", tickLine: false, axisLine: false, tickFormatter: v => `₹${Math.round(v / 1000)}k` }), _jsx(Tooltip, { formatter: (v) => [`₹${Number(v).toLocaleString("en-IN")}`, "Spent"], contentStyle: { background: "var(--surface-strong)", border: "1px solid var(--line)", borderRadius: 8, color: "var(--text)" } }), _jsx(Bar, { dataKey: "amount", fill: "var(--accent)", radius: [3, 3, 0, 0] })] }) }) });
}
export function CategoryDonut({ data }) {
    return _jsx("div", { className: "chart chart-donut", children: _jsx(ResponsiveContainer, { width: "100%", height: 260, children: _jsxs(PieChart, { children: [_jsx(Pie, { data: data, dataKey: "amount", nameKey: "name", innerRadius: 68, outerRadius: 92, paddingAngle: 2, children: data.map((_, i) => _jsx(Cell, { fill: palette[i % palette.length] }, i)) }), _jsx(Tooltip, { formatter: (v) => [`₹${Number(v).toLocaleString("en-IN")}`, "Spend"], contentStyle: { background: "var(--surface-strong)", border: "1px solid var(--line)", borderRadius: 8, color: "var(--text)" } })] }) }) });
}
export function TrendArea({ data }) {
    return _jsx("div", { className: "chart", children: _jsx(ResponsiveContainer, { width: "100%", height: 260, children: _jsxs(AreaChart, { data: data, margin: { top: 8, right: 10, left: -18, bottom: 0 }, children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "areaFill", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "var(--accent)", stopOpacity: 0.28 }), _jsx("stop", { offset: "100%", stopColor: "var(--accent)", stopOpacity: 0 })] }) }), _jsx(CartesianGrid, { vertical: false, stroke: "var(--line)" }), _jsx(XAxis, { dataKey: "month", stroke: "var(--muted)", tickLine: false, axisLine: false }), _jsx(YAxis, { stroke: "var(--muted)", tickLine: false, axisLine: false, tickFormatter: v => `₹${Math.round(v / 1000)}k` }), _jsx(Tooltip, { formatter: (v) => [`₹${Number(v).toLocaleString("en-IN")}`, "Spend"], contentStyle: { background: "var(--surface-strong)", border: "1px solid var(--line)", borderRadius: 8, color: "var(--text)" } }), _jsx(Area, { type: "monotone", dataKey: "amount", stroke: "var(--accent)", strokeWidth: 2, fill: "url(#areaFill)" })] }) }) });
}
